root = "."
testdata_dir = "testdata"
tmp_dir = ".tmp"

[build]
	#pre_cmd = ["curl", "localhost:8080/_notify"]
	pre_cmd = ["pgrep wasm && curl localhost:8080/_notify || $(which wasmserve) ."]
  args_bin = []
	cmd = "echo noop"
	# This is for the local executable
  #cmd = "GOOS=windows go build -o ./.tmp/main ."
  #bin = "./.tmp/main"
  delay = 500
  exclude_dir = [".tmp"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
